Slack integration
khageshsaini/envoy-app-deployer pull request #4
Opened 2021-11-29 10:24 UTC by 7azycoder

2021-11-30 09:31 UTC, 7azycoder commented
jq needs to be installed.

2021-12-08 06:53 UTC, khageshsaini requested changes

2021-12-08 06:53 UTC, khageshsaini commented on Envoy.blade.php
> +    require_once 'src/slack.php';
indent

2021-12-08 06:53 UTC, khageshsaini commented on Envoy.blade.php
> +@task('notify', ['on' => end($remote_keys)])
```suggestion
@task('notify_on_slack', ['on' => end($remote_keys)])
```

2021-12-08 07:11 UTC, merged